/**
 * @ Create Time: 2022-06-21 16:50:28
 * @ Modified time: 2022-06-21 18:11:45
 * @ Description:  定义文件图标，这里支持 20 种 图标样式
 */

const fileIcons = {
  defaultIcon: { name: 'file' },
  icons: [
    { name: 'html', fileExtensions: ['htm', 'html', 'xhtml', 'html_vm', 'asp'] },
    { name: 'css', fileExtensions: ['css'] },
    {
      name: 'json',
      fileExtensions: ['json', 'jsonc', 'tsbuildinfo', 'json5', 'jsonl', 'ndjson'],
    },
    {
      name: 'image',
      fileExtensions: [
        'png',
        'jpeg',
        'jpg',
        'gif',
        'ico',
        'tif',
        'tiff',
        'psd',
        'psb',
        'ami',
        'apx',
        'avif',
        'bmp',
        'bpg',
        'brk',
        'cur',
        'dds',
        'dng',
        'exr',
        'fpx',
        'gbr',
        'img',
        'jbig2',
        'jb2',
        'jng',
        'jxr',
        'pgf',
        'pic',
        'raw',
        'webp',
        'eps',
        'afphoto',
        'ase',
        'aseprite',
        'clip',
        'cpt',
        'heif',
        'heic',
        'kra',
        'mdp',
        'ora',
        'pdn',
        'reb',
        'sai',
        'tga',
        'xcf',
        'jfif',
        'ppm',
        'pbm',
        'pgm',
        'pnm',
      ],
    },
    { name: 'javascript', fileExtensions: ['esx', 'mjs', 'js'] },
    { name: 'pdf', fileExtensions: ['pdf'] },
    {
      name: 'zip',
      fileExtensions: [
        'zip',
        'tar',
        'gz',
        'xz',
        'lzma',
        'lz4',
        'br',
        'bz2',
        'bzip2',
        'gzip',
        'brotli',
        '7z',
        'rar',
        'tz',
        'txz',
        'tgz',
      ],
    },
    { name: 'exe', fileExtensions: ['exe', 'msi'] },
    {
      name: 'console',
      fileExtensions: [
        'sh',
        'ksh',
        'csh',
        'tcsh',
        'zsh',
        'bash',
        'bat',
        'cmd',
        'awk',
        'fish',
        'exp',
      ],
    },

    { name: 'word', fileExtensions: ['doc', 'docx', 'rtf', 'odt'] },

    {
      name: 'font',
      fileExtensions: [
        'woff',
        'woff2',
        'ttf',
        'eot',
        'suit',
        'otf',
        'bmap',
        'fnt',
        'odttf',
        'ttc',
        'font',
        'fonts',
        'sui',
        'ntf',
        'mrf',
      ],
    },
    {
      name: 'powerpoint',
      fileExtensions: [
        'pptx',
        'ppt',
        'pptm',
        'potx',
        'potm',
        'ppsx',
        'ppsm',
        'pps',
        'ppam',
        'ppa',
        'odp',
      ],
    },
    {
      name: 'table',
      fileExtensions: ['xlsx', 'xlsm', 'xls', 'csv', 'tsv', 'psv', 'ods'],
    },
    {
      name: 'video',
      fileExtensions: [
        'webm',
        'mkv',
        'flv',
        'vob',
        'ogv',
        'ogg',
        'gifv',
        'avi',
        'mov',
        'qt',
        'wmv',
        'yuv',
        'rm',
        'rmvb',
        'mp4',
        'm4v',
        'mpg',
        'mp2',
        'mpeg',
        'mpe',
        'mpv',
        'm2v',
      ],
    },
    {
      name: 'audio',
      fileExtensions: ['mp3', 'flac', 'm4a', 'wma', 'aiff', 'wav'],
    },
    { name: 'document', fileExtensions: ['txt'] },

    {
      name: 'android',
      fileExtensions: ['apk', 'smali', 'dex'],
    },
    { name: 'log', fileExtensions: ['log'] },
    { name: 'svg', fileExtensions: ['svg'] },
  ],
};

export default fileIcons;
